### ISSUE TITLE
Profile memory usage

### ISSUE THREAD

**Issue by objorke** [UsageStats/UsageStats#4]
**This issue was imported from [CodePlex](http://UsageStats.codeplex.com/workitem/993)**

**[objo](http://www.codeplex.com/site/users/view/objo)** wrote 2013-10-17 at 18:17
Check for memory leaks. Reduce memory footprint?

**Comment by PaulHuxe** [comment]
I'm not sure this issue is still an issue: I ran the process 6 hours long and monitored the memory usage.
The memory used started at 22 MB, then quickly growed up to 28 MB when checking all the menu options.
During the 6 next hours, it slowly growed to max 31 MB and decreased to 28 MB again when the GarbageCollector did its work;
No noticeable increase of the amount of objects in the paged memory or in the heap. 
Didn't see anything looking like a memory leak, and I'm not sure 30 MB is a real problem for modern computers.

**Comment by sadortun** [comment]
Thanks @PaulHuxe I'll close this.
